# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wshela <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/06/23 15:52:26 by wshela            #+#    #+#              #
#    Updated: 2019/06/23 16:02:10 by wshela           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = program

FILES = calc.c

OFILES = calc.o

HEADER = head.h

all:
	gcc  $(FILES) -L. -lone -o $(NAME)

clear:
	rm program

